name: CI

on:
  push, pull_request:

jobs:
  lint:
    uses: dvsa/.github/.github/workflows/nodejs-lint.yaml@v2.3

  test:
    uses: dvsa/.github/.github/workflows/nodejs-test.yaml@v2.3

  security:
    uses: dvsa/.github/.github/workflows/nodejs-security.yaml@v2.3
    with:
      args: --all-projects
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    uses: dvsa/.github/.github/workflows/nodejs-build.yaml@v2.3
    with:
      upload_artifact: true
      build_folder: package
      build_folder_path: dist
      retention_days: 3
      build_command: build
      