name: CI

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    uses: dvsa/.github/.github/workflows/nodejs-lint.yaml@v2.3

  test:
    uses: dvsa/.github/.github/workflows/nodejs-test.yaml@v2.3

  security:
    uses: dvsa/.github/.github/workflows/nodejs-security.yaml@v2.3
    with:
      args: --all-projects
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    uses: dvsa/.github/.github/workflows/nodejs-build.yaml@v2.3
    with:
      upload_artifact: true
      build_folder: package
      build_folder_path: dist
      retention_days: 3
      build_command: build
  
  something:
    if: startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/heads/fix/') || startsWith(github.ref, 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - name: echo something
        run: |
          echo "Hello, World!"

  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo startsWith(github.ref, 'refs/heads/feature/')
      